additionalProperties:
  groupId: org.openapitools
  artifactDescription: OpenAPI Java
  artifactId: openapi-spring
  artifactUrl: 'https://github.com/yo41sawada/stoplight-sample/tree/main/out/java'
  artifactVersion: 1.0.0
  apipackage: org.openapitools.api
  basePackage: org.openapitools
  invokerPackage: org.openapitools.api
  modelpackage: org.openapitools.model
  configPackage: org.openapitools.configuration
